services:
  db:
    image: postgis/postgis:16-3.4
    container_name: oei-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./apps/api
    container_name: oei-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api/app:/app/app  # hot reload
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  frontend:
    build:
      context: ./apps/frontend
    container_name: oei-frontend
    working_dir: /app
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - .env 
    command: sh -c "npm install && npm run dev:docker"
    ports:
      - "5173:5173"

volumes:
  db_data:
