"""Add orbital-pass model

Revision ID: 0ebdf121f1dc
Revises: 9bdc2a60042e
Create Date: 2025-08-20 19:56:18.472158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "0ebdf121f1dc"
down_revision: Union[str, Sequence[str], None] = "9bdc2a60042e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orbital_passes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.Column("aoi_id", sa.Integer(), nullable=False),
        sa.Column("tle_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_elevation_deg", sa.Float(), nullable=False),
        sa.Column("max_elevation_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "track_geom",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("min_elevation_deg", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_time > start_time", name="ck_pass_time_order"),
        sa.CheckConstraint(
            "max_elevation_deg >= 0 AND max_elevation_deg <= 90",
            name="ck_pass_max_el_range",
        ),
        sa.CheckConstraint(
            "max_elevation_time >= start_time AND max_elevation_time <= end_time",
            name="ck_pass_peak_within_window",
        ),
        sa.ForeignKeyConstraint(["aoi_id"], ["aois.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["satellite_id"], ["satellites.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tle_id"], ["tles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index(
    #     "idx_orbital_passes_track_geom",
    #     "orbital_passes",
    #     ["track_geom"],
    #     unique=False,
    #     postgresql_using="gist",
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_orbital_passes_track_geom",
        table_name="orbital_passes",
        postgresql_using="gist",
    )
    op.drop_table("orbital_passes")
    # ### end Alembic commands ###
