"""init schema

Revision ID: 9bdc2a60042e
Revises:
Create Date: 2025-08-18 15:08:24.079384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "9bdc2a60042e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aois",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.create_index(
    #     "idx_aois_geometry", "aois", ["geometry"], unique=False, postgresql_using="gist"
    # )
    op.create_index(op.f("ix_aois_id"), "aois", ["id"], unique=False)
    op.create_table(
        "satellites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("norad_id", name="uq_sat_norad"),
    )
    op.create_table(
        "tles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("line1", sa.String(length=80), nullable=False),
        sa.Column("line2", sa.String(length=80), nullable=False),
        sa.Column("epoch_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("satnum", sa.Integer(), nullable=False),
        sa.Column("intl_desg", sa.String(length=11), nullable=True),
        sa.Column("inclination_deg", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("raan_deg", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("eccentricity", sa.Numeric(precision=9, scale=7), nullable=False),
        sa.Column("arg_perigee_deg", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("mean_anomaly_deg", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column(
            "mean_motion_rev_per_day", sa.Numeric(precision=12, scale=8), nullable=False
        ),
        sa.Column("bstar", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("rev_number", sa.Integer(), nullable=True),
        sa.Column("checksum_ok_l1", sa.Boolean(), nullable=False),
        sa.Column("checksum_ok_l2", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["satellite_id"], ["satellites.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("satellite_id", "epoch_utc", name="uq_tle_sat_epoch"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tles")
    op.drop_table("satellites")
    op.drop_index(op.f("ix_aois_id"), table_name="aois")
    op.drop_index("idx_aois_geometry", table_name="aois", postgresql_using="gist")
    op.drop_table("aois")
    # ### end Alembic commands ###
